### ISSUE TITLE
calc.so not found

### ISSUE THREAD

**Issue by niksingh710** [svenstaro/rofi-calc#107]
```bash

(process:213768): Rofi-WARNING **: 10:57:28.637: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007
```
recently started facing this

**Comment by svenstaro** [comment]
Did you update rofi without rebuilding rofi-calc?

**Comment by niksingh710** [comment]
> Did you update rofi without rebuilding rofi-calc?

I guess yes.
But then I removed `rofi-calc` and re-installed it from aur.

**Comment by svenstaro** [comment]
So it works now?

**Comment by niksingh710** [comment]
> So it works now?

No it does not

Gives me same error.

**Comment by niksingh710** [comment]
one thing i forgot to mention is i am using `rofi-lbonn-wayland-git` on arch linux it is from https://github.com/lbonn/rofi

**Comment by joshpetit** [comment]
I get the same error

**Comment by YasserKa** [comment]
It works with `rofi`, but not with `rofi-lbonn-wayland-git`

**Comment by joshpetit** [comment]
I was using rofi-git, but switched to just rofi and it worked. Thanks @YasserKa

**Comment by svenstaro** [comment]
So can we consider this fixed?

**Comment by joshpetit** [comment]
I'd say for most it's fixed, but I imagine this would be a problem for anyone who's running rofi-git to get the latest changes. Could there be a way to make it work with it?

**Comment by svenstaro** [comment]
I'm not sure what the problem is here though. I suppose it would just need a rebuild since it's complaining about the ABI?

**Comment by joshpetit** [comment]
I'm not familiar with C so couldn't tell you, but for my purposes it's fixed and until someone who needs rofi-git comments on this I think you can consider it solved.

**Comment by Rolv-Apneseth** [comment]
I think this issue should maybe be reopened. Similar issues with this plugin, mine and [rofi-emoji](https://github.com/Mange/rofi-emoji). Potential cause and fix referenced in an issue for `rofi-emoji` [here](https://github.com/Mange/rofi-emoji/issues/65). Seems to be an update to a rofi dependency which is not yet in a rofi release, but may be a problem for updated rofi versions in the future. Hope that's of some use, though I can't be of much more help since I used an [awesome library](https://github.com/SabrinaJewson/rofi-mode.rs) to write my one so I don't actually know how the underlying C stuff works.
