### ISSUE TITLE
Spawning child failed: Too many open files after 3 minutes

### ISSUE THREAD

**Issue by kaistian** [svenstaro/rofi-calc#42]
I run the command `rofi -show calc -modi calc -no-show-match -no-sort`
In the calc: input I can write anything like `2` and wait 3 minutes and it core dumps with the following message

```
$ time rofi -show calc -modi calc -no-show-match -no-sort

** (process:32089): ERROR **: 22:04:20.115: Spawning child failed: Too many open files
Trace/breakpoint trap (core dumped)

real	3m10,419s
user	0m47,474s
sys	0m21,516s
```

Using:
> rofi v1.5.4
> rofi-calc 1.6
> ulimit open files set to 1024

**Comment by nonchip** [comment]
since the `qalc` processes are spawned in what feels to be an endless loop and `process_cb` is called asynchronously i suspect they keep getting spawned faster than they die off, which results in their stdout pipes piling up until the kernel just says nope.

figuring out a way to prevent respawning it unless there was an actual change in the input sounds like the way to go (this might tie into the changes required for #40 too).

**Comment by svenstaro** [comment]
Ok I have 0 clue why that's happening. Do qalculate and rofi work by themselves?

**Comment by kaistian** [comment]
They both is working flawlessly, i have qalc running in a terminal at all time, and using rofi daily for windows switching and start of programs.

The process creates a lot of pipes, and this is right before it crashes
```
$ ls /proc/2390/fd/ | wc -l; ls -lt /proc/2390/fd/ | head
1018
total 0
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1009 -> pipe:[28681302]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1010 -> pipe:[28669514]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1011 -> pipe:[28669516]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1012 -> pipe:[28680509]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1013 -> pipe:[28680512]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1014 -> pipe:[28688987]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1015 -> pipe:[28689489]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1016 -> pipe:[28677861]
lr-x------ 1 kaistian kaistian 64 mars   4 18:06 1017 -> pipe:[28689491]
```

**Comment by svenstaro** [comment]
Really weird. Do you have something like SELinux?

**Comment by kaistian** [comment]
I have tested on two machines and it core dumps on both.
One of them is Kubuntu 19.10 and run Apparmor but nothing in the log about rofi/qalc.
The other machine is Void Linux that has nothing like that installed.

Does this mean you can't reproduce this?

**Comment by nonchip** [comment]
> The process creates a lot of pipes, and this is right before it crashes

as i said, processes are spawned endlessly and asynchronously, this is kinda expected behaviour in my eyes.

it essentially boils down whether rofi calling `calc_preprocess_input` in an endless loop is faster (-> crash) or slower (-> not reproducible) than the kernel is starting qalc (asynchronously), qalc doing its thing and exiting, and the `process_cb` being called (again asynchronously) by gtk, which then finally closes the pipe in `g_subprocess_wait_check_finish`.  
i imagine on most setups it's gonna be the former, and just a matter of how fast those pipes pile up and how many you can have until it dies.

**Comment by svenstaro** [comment]
Thanks for the help guys. This commit fixes it for me. Please give it a spin. If it's good for you, I'll cut a release.

**Comment by kaistian** [comment]
Have tested master and it's fixed for too, thanks you for the fix.

**Comment by svenstaro** [comment]
Made release v1.7 that has this fix. At the same time, I moved this to official Arch Linux repos.
